# Generated by Django 5.2.4 on 2025-10-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_session_key_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('в обработке', 'В обработке'), ('успешно', 'Успешно'), ('ошибка', 'Ошибка')], default='в обработке', max_length=15),
        ),
    ]
