# Generated by Django 5.2.4 on 2025-07-23 04:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_delivery_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sea_delivery_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gtd_rb_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dt_rf_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='manufacturers/')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='site/')),
                ('favicon', models.ImageField(blank=True, upload_to='site/')),
                ('default_meta_title', models.CharField(blank=True, max_length=200)),
                ('default_meta_description', models.CharField(blank=True, max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('map_embed_code', models.TextField(blank=True)),
                ('copyright_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('new', 'Yangi buyurtma'), ('processing', 'Tayyorlanmoqda'), ('shipped', 'Yuborilgan'), ('customs', 'Bojiqada'), ('ready', 'Topshirishga tayyor'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], default='new', max_length=20)),
                ('delivery_type', models.CharField(choices=[('air', 'Aviakuryer'), ('sea', 'Dengiz orqali')], max_length=10)),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('document_type', models.CharField(choices=[('gtd_rb', 'GTD RB'), ('dt_rf', 'DT RF')], max_length=10)),
                ('document_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('shipping_address', models.TextField()),
                ('billing_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi buyurtma'), ('processing', 'Tayyorlanmoqda'), ('shipped', 'Yuborilgan'), ('customs', 'Bojiqada'), ('ready', 'Topshirishga tayyor'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='asic.order')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asic.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('hash_rate', models.CharField(blank=True, max_length=100)),
                ('power_consumption', models.CharField(blank=True, max_length=100)),
                ('algorithm', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='media/products')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asic.manufacturer')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asic.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Chegirma nomi')),
                ('discount_type', models.CharField(choices=[('percentage', 'Foizli chegirma'), ('fixed', 'Aniq summa')], default='percentage', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma qiymati')),
                ('apply_to', models.CharField(choices=[('all', 'Barcha mahsulotlar'), ('category', 'Maxsus kategoriya'), ('product', 'Maxsus mahsulot'), ('manufacturer', 'Ishlab chiqaruvchi')], default='all', max_length=12)),
                ('start_date', models.DateTimeField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateTimeField(verbose_name='Tugash sanasi')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimal buyurtma summasi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturers', models.ManyToManyField(blank=True, to='asic.manufacturer', verbose_name='Ishlab chiqaruvchilar')),
                ('products', models.ManyToManyField(blank=True, to='asic.product', verbose_name='Mahsulotlar')),
                ('categories', models.ManyToManyField(blank=True, to='asic.productcategory', verbose_name='Kategoriyalar')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
