# Generated by Django 5.2.4 on 2025-11-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_page',
            name='banner_bg',
            field=models.ImageField(null=True, upload_to='media/sitesettings', verbose_name='Banner'),
        ),
    ]
