# Generated by Django 5.2.4 on 2025-07-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0002_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='media/banners')),
                ('title', models.CharField(max_length=1000)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='address',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='copyright_text',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='map_embed_code',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('air', 'Авиакурьер'), ('sea', 'По морю')], max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'Подготовка'), ('shipped', 'Отправил'), ('ready', 'Готов отправить'), ('completed', 'Завершенный'), ('cancelled', 'Отменено')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'Подготовка'), ('shipped', 'Отправил'), ('ready', 'Готов отправить'), ('completed', 'Завершенный'), ('cancelled', 'Отменено')], max_length=20),
        ),
    ]
