# Generated by Django 5.2.4 on 2026-01-28 09:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0002_alter_about_page_banner_bg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'verbose_name': 'Banner', 'verbose_name_plural': 'Bannerlar'},
        ),
        migrations.AlterModelOptions(
            name='coin',
            options={'verbose_name': 'Texnik', 'verbose_name_plural': 'Texnik'},
        ),
        migrations.AlterModelOptions(
            name='deliveryinfo',
            options={'verbose_name': 'Yetkazib berish (kontent)', 'verbose_name_plural': 'Yetkazib berish (kontent)'},
        ),
        migrations.AlterModelOptions(
            name='deliverysettings',
            options={'verbose_name': 'Yetkazib berish sozlamasi', 'verbose_name_plural': 'Yetkazib berish sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Chegirma', 'verbose_name_plural': 'Chegirmalar'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Brend', 'verbose_name_plural': 'Brendlar'},
        ),
        migrations.AlterModelOptions(
            name='office',
            options={'verbose_name': 'Ofis', 'verbose_name_plural': 'Ofislar'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma', 'verbose_name_plural': 'Buyurtmalar'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Buyurtma pozitsiyasi', 'verbose_name_plural': 'Buyurtma pozitsiyalari'},
        ),
        migrations.AlterModelOptions(
            name='orderstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Buyurtma holati tarixi', 'verbose_name_plural': 'Buyurtma holatlari tarixi'},
        ),
        migrations.AlterModelOptions(
            name='orderstatusrule',
            options={'verbose_name': 'Buyurtma holati qoidasi', 'verbose_name_plural': 'Buyurtma holati qoidalari'},
        ),
        migrations.AlterModelOptions(
            name='pagetitle',
            options={'verbose_name': 'Sahifa sarlavhasi', 'verbose_name_plural': 'Sahifa sarlavhalari'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at'], 'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Kategoriya', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profil', 'verbose_name_plural': 'Profillar'},
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Sayt sozlamasi', 'verbose_name_plural': 'Sayt sozlamalari'},
        ),
        migrations.AlterModelOptions(
            name='staticpage',
            options={'verbose_name': 'Statik sahifa', 'verbose_name_plural': 'Statik sahifalar'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='algorithm',
        ),
        migrations.RemoveField(
            model_name='product',
            name='coins',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hash_rate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='hash_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='power_consumption',
        ),
        migrations.RemoveField(
            model_name='product',
            name='temprature',
        ),
        migrations.AddField(
            model_name='product',
            name='default_variant_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Variant uchun boshlangich zaxira'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO description'),
        ),
        migrations.AddField(
            model_name='product',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_colors',
            field=models.CharField(blank=True, help_text='Masalan: black, brown, white', max_length=200, verbose_name='Ranglar (vergul bilan)'),
        ),
        migrations.AddField(
            model_name='product',
            name='variant_sizes',
            field=models.CharField(blank=True, help_text='Masalan: 40, 41, 42', max_length=200, verbose_name="O'lchamlar (vergul bilan)"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO description (umumiy)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='SEO title (umumiy)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='OpenGraph rasm'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='about_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='about_title',
            field=models.TextField(blank=True, null=True, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='benefit_text',
            field=models.TextField(blank=True, null=True, verbose_name='Afzallik matn'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='benefit_title',
            field=models.TextField(blank=True, null=True, verbose_name='Afzallik sarlavha'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='card1',
            field=models.TextField(blank=True, null=True, verbose_name='Karta 1 matn'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='card2',
            field=models.TextField(blank=True, null=True, verbose_name='Karta 2 matn'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='office_text',
            field=models.TextField(blank=True, null=True, verbose_name='Ofislar matn'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='office_title',
            field=models.TextField(blank=True, null=True, verbose_name='Ofislar sarlavha'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='why_us',
            field=models.TextField(blank=True, null=True, verbose_name='Nega biz'),
        ),
        migrations.AlterField(
            model_name='about_page',
            name='why_us_title',
            field=models.TextField(blank=True, null=True, verbose_name='Nega biz sarlavha'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='number',
            field=models.CharField(max_length=10, verbose_name='Raqam'),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='text',
            field=models.CharField(max_length=100, verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ImageField(upload_to='media/banners', verbose_name='Banner'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='benefit_text',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='benefit_title',
            field=models.TextField(verbose_name='Nega biz'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='title',
            field=models.CharField(max_length=1000, verbose_name='Sarlavha'),
        ),
        migrations.AlterField(
            model_name='cards',
            name='is_about',
            field=models.BooleanField(default=False, verbose_name='Biz haqimizda'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='coin_icons/', verbose_name='Ikonka'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=10, unique=True, verbose_name='Belgi'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='air_title',
            field=models.CharField(default='Ekspress (1-2 kun)', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='courier_title',
            field=models.CharField(default='Kuryer (2-5 kun)', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='free_shipping_text',
            field=models.CharField(default="1000000 so'mdan yuqori buyurtma uchun bepul", max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='important_info_body',
            field=models.TextField(default='Har bir mahsulot sifat nazoratidan otadi. Original va kafolatli mahsulotlar.'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='important_info_title',
            field=models.CharField(default='Muhim:', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='main_text',
            field=models.CharField(blank=True, default='', max_length=900, null=True, verbose_name='Asosiy matn'),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='paid_shipping_text',
            field=models.CharField(default="1000000 so'mgacha: 25000-50000 so'm", max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='sea_title',
            field=models.CharField(default='Olib ketish (shaxsiy)', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='title',
            field=models.CharField(default='Yetkazib berish haqida', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='air_delivery_name',
            field=models.CharField(default='Kuryer', max_length=255, verbose_name='Kuryer nomi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='air_delivery_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kuryer tarifi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='auto_delivery_name',
            field=models.CharField(default='Ekspress', max_length=255, verbose_name='Ekspress nomi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='auto_delivery_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ekspress tarifi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='dt_rf_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Hisob-faktura foizi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='dt_rf_name',
            field=models.CharField(default='Hisob-faktura', max_length=255, verbose_name='Hisob-faktura nomi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='gtd_rb_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kvitansiya foizi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='gtd_rb_name',
            field=models.CharField(default='Kvitansiya', max_length=255, verbose_name='Kvitansiya nomi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='sea_delivery_name',
            field=models.CharField(default='Olib ketish', max_length=255, verbose_name='Olib ketish nomi'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='sea_delivery_rate',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Olib ketish tarifi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='apply_to',
            field=models.CharField(choices=[('all', 'Barcha mahsulotlar'), ('category', 'Kategoriya'), ('product', 'Mahsulot'), ('manufacturer', 'Brend')], default='all', max_length=12, verbose_name='Qollash turi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='categories',
            field=models.ManyToManyField(blank=True, to='asic.productcategory', verbose_name='Kategoriyalar'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Foizli chegirma'), ('fixed', 'Doimiy summa')], default='percentage', max_length=10, verbose_name='Chegirma turi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='end_date',
            field=models.DateTimeField(verbose_name='Tugash sanasi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='manufacturers',
            field=models.ManyToManyField(blank=True, to='asic.manufacturer', verbose_name='Brendlar'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='max_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maksimal buyurtma summasi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Minimal buyurtma summasi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Chegirma nomi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='products',
            field=models.ManyToManyField(blank=True, to='asic.product', verbose_name='Mahsulotlar'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='start_date',
            field=models.DateTimeField(verbose_name='Boshlanish sanasi'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Chegirma qiymati'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='description',
            field=models.TextField(blank=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(upload_to='manufacturers/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Brend nomi'),
        ),
        migrations.AlterField(
            model_name='office',
            name='image',
            field=models.ImageField(upload_to='offices', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='office',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='office',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='order',
            name='billing_address',
            field=models.TextField(blank=True, verbose_name="To'lov manzili"),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Yetkazib berish narxi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('courier', 'Kuryer'), ('pickup', 'Olib ketish'), ('express', 'Ekspress')], max_length=10, verbose_name='Yetkazib berish turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma summasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chegirma foizi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Hujjat narxi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='document_type',
            field=models.CharField(choices=[('receipt', 'Kvitansiya'), ('invoice', 'Hisob-faktura')], max_length=10, verbose_name='Hujjat turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Holat yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Buyurtma raqami'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, verbose_name="To'lov ID"),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20, verbose_name="To'lov holati"),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(verbose_name='Yetkazib berish manzili'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi buyurtma'), ('processing', 'Jarayonda'), ('shipped', 'Yuborildi'), ('customs', 'Bojxonada'), ('sorting', 'Saralash markazida'), ('delivering', 'Yetkazilmoqda'), ('pickup_ready', 'Olib ketishga tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Oraliq summa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami summa'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Chegirma summasi'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='asic.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Asl narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asic.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Miqdor'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='asic.order', verbose_name='Buyurtma'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi buyurtma'), ('processing', 'Jarayonda'), ('shipped', 'Yuborildi'), ('customs', 'Bojxonada'), ('sorting', 'Saralash markazida'), ('delivering', 'Yetkazilmoqda'), ('pickup_ready', 'Olib ketishga tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='days_after',
            field=models.PositiveIntegerField(help_text='Necha kundan keyin ushbu holatga otadi?'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='immediate',
            field=models.BooleanField(default=False, verbose_name='Darhol qollansinmi?'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='order_priority',
            field=models.PositiveIntegerField(default=0, help_text='Ustuvorlik raqami (kichikdan boshlanadi)'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi buyurtma'), ('processing', 'Jarayonda'), ('shipped', 'Yuborildi'), ('customs', 'Bojxonada'), ('sorting', 'Saralash markazida'), ('delivering', 'Yetkazilmoqda'), ('pickup_ready', 'Olib ketishga tayyor'), ('completed', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Biz haqimizda'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='cart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Savatcha'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='catalog',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Katalog'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='checkout',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Buyurtma rasmiylash'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='detail',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mahsulot tafsiloti'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='home',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bosh sahifa'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kirish'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='payment_deliver',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tolov va yetkazib berish'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='privacy',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maxfiylik siyosati'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Profil'),
        ),
        migrations.AlterField(
            model_name='pagetitle',
            name='register',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Royxatdan otish'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='payment_del',
            field=models.TextField(blank=True, null=True, verbose_name='Yetkazib berish matni'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='payment_del_title',
            field=models.TextField(blank=True, null=True, verbose_name='Yetkazib berish sarlavha'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='payment_pay',
            field=models.TextField(blank=True, null=True, verbose_name='Tolov matni'),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='payment_title',
            field=models.TextField(blank=True, null=True, verbose_name='Tolov sarlavha'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='asic.productcategory', verbose_name='Kategoriya'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name="Qo'shimcha rasm 1"),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name="Qo'shimcha rasm 2"),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='media/products', verbose_name='Asosiy rasm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faol'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Tavsiya etiladi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asic.manufacturer', verbose_name='Brend'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Mahsulot nomi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Eski narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, verbose_name='Xususiyatlar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Jami zaxira'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Yangilangan sana'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Kategoriya nomi'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asic.productcategory', verbose_name='Ota kategoriya'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pochta indeksi'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kocha'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mamlakat'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Uy'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='checkout_text',
            field=models.TextField(blank=True, null=True, verbose_name='Checkout matni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='favicon',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Footer matni'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='iframe_code',
            field=models.TextField(blank=True, null=True, verbose_name='Ofis manzili'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(upload_to='site/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(max_length=100, verbose_name='Sayt nomi'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='VK'),
        ),
        migrations.AlterField(
            model_name='templateedit',
            name='about_subtitle',
            field=models.TextField(blank=True, null=True, verbose_name='Biz haqimizda subtitle'),
        ),
        migrations.AlterField(
            model_name='templateedit',
            name='about_title',
            field=models.TextField(blank=True, null=True, verbose_name='Biz haqimizda sarlavha'),
        ),
        migrations.AlterField(
            model_name='templateedit',
            name='payment_del',
            field=models.TextField(blank=True, null=True, verbose_name='Yetkazib berish matni'),
        ),
        migrations.AlterField(
            model_name='templateedit',
            name='payment_pay',
            field=models.TextField(blank=True, null=True, verbose_name='Tolov matni'),
        ),
        migrations.AlterField(
            model_name='templateedit',
            name='privacy_text',
            field=models.TextField(blank=True, null=True, verbose_name='Maxfiylik matni'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Rang')),
                ('size', models.CharField(max_length=20, verbose_name="O'lcham")),
                ('sku', models.CharField(max_length=120, unique=True, verbose_name='SKU')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Zaxira')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='asic.product')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variantlar',
                'ordering': ['color', 'size'],
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asic.productvariant', verbose_name='Variant'),
        ),
    ]
