# Generated by Django 5.2.4 on 2026-01-31 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0003_alter_bannerimage_options_alter_coin_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asic.productcategory', verbose_name=' kategoriya'),
        ),
    ]
