# Generated by Django 5.2.4 on 2025-07-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0003_bannerimage_remove_sitesettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
