# Generated by Django 5.2.4 on 2025-07-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0004_bannerimage_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='coin_icons/')),
            ],
        ),
    ]
