# Generated by Django 5.2.4 on 2025-07-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0005_coin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coins',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='asic.coin'),
        ),
    ]
