# Generated by Django 5.2.4 on 2025-07-24 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0006_product_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images2',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='images3',
            field=models.ImageField(blank=True, null=True, upload_to='media/products'),
        ),
    ]
