# Generated by Django 5.2.4 on 2025-07-24 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0007_product_images2_product_images3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='images2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='images3',
            new_name='image3',
        ),
    ]
