# Generated by Django 5.2.4 on 2025-07-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0008_rename_images2_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
