# Generated by Django 5.2.4 on 2025-07-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0010_product_image2_product_image3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
