# Generated by Django 5.2.4 on 2025-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0012_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('vkontakte', models.CharField(max_length=200)),
                ('telegram', models.CharField(max_length=200)),
                ('whatsapp', models.CharField(max_length=200)),
            ],
        ),
    ]
