# Generated by Django 5.2.4 on 2025-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0013_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='image',
            field=models.ImageField(default=1, upload_to='offices'),
            preserve_default=False,
        ),
    ]
