# Generated by Django 5.2.4 on 2025-07-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0014_office_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_meta_description',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_meta_title',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='youtube',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
