# Generated by Django 5.2.4 on 2025-07-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0015_delete_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='coins',
            field=models.ManyToManyField(blank=True, related_name='products', to='asic.coin'),
        ),
    ]
