# Generated by Django 5.2.4 on 2025-08-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0017_alter_bannerimage_options_alter_coin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
