# Generated by Django 5.2.4 on 2025-08-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0019_profile_father_name_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hash_rate',
            field=models.IntegerField(blank=True, verbose_name='Хешрейт'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power_consumption',
            field=models.IntegerField(blank=True, verbose_name='Потребление энергии'),
        ),
    ]
