# Generated by Django 5.2.4 on 2025-08-12 15:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0020_alter_product_hash_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
