# Generated by Django 5.2.4 on 2025-08-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0021_alter_staticpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hash_unit',
            field=models.CharField(choices=[('TH', 'TH/s'), ('GH', 'GH/s'), ('MH', 'MH/s')], default='TH', max_length=2),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='manufacturers/', verbose_name='Логотип'),
        ),
    ]
