# Generated by Django 5.2.4 on 2025-08-14 02:01

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0022_product_hash_unit_alter_manufacturer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='raw_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staticpage',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
