# Generated by Django 5.2.4 on 2025-08-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0023_staticpage_raw_html_alter_staticpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverysettings',
            name='dt_rf_cost',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Процент от общей суммы корзины'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='gtd_rb_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент от общей суммы корзины'),
        ),
    ]
