# Generated by Django 5.2.4 on 2025-08-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0024_alter_deliverysettings_dt_rf_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='air_delivery_name',
            field=models.CharField(default='Авиадоставка', max_length=255, verbose_name='Название тарифа авиадоставки'),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='auto_delivery_name',
            field=models.CharField(default='Морская доставка', max_length=255, verbose_name='Название тарифа Авто доставки'),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='auto_delivery_rate',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12, verbose_name='Тариф Авто доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='dt_rf_name',
            field=models.CharField(default='DT/RF', max_length=255, verbose_name='Название DT/RF'),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='gtd_rb_name',
            field=models.CharField(default='GTD/RB', max_length=255, verbose_name='Название GTD/RB'),
        ),
        migrations.AddField(
            model_name='deliverysettings',
            name='sea_delivery_name',
            field=models.CharField(default='Морская доставка', max_length=255, verbose_name='Название тарифа морской доставки'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='dt_rf_cost',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5, verbose_name='Процент DT/RF'),
        ),
        migrations.AlterField(
            model_name='deliverysettings',
            name='gtd_rb_cost',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5, verbose_name='Процент GTD/RB'),
        ),
    ]
