# Generated by Django 5.2.4 on 2025-08-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0025_deliverysettings_air_delivery_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
