# Generated by Django 5.2.4 on 2025-08-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0026_profile_address_city_profile_address_postal_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=4000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', models.TextField(blank=True, null=True, verbose_name='privacy text')),
                ('about_title', models.TextField(blank=True, null=True, verbose_name='About title')),
                ('about_subtitle', models.TextField(blank=True, null=True, verbose_name='About subtitle')),
                ('payment_pay', models.TextField(blank=True, null=True, verbose_name='Оплата text')),
                ('payment_del', models.TextField(blank=True, null=True, verbose_name='Доставка  text')),
            ],
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='checkout_text',
            field=models.TextField(blank=True, null=True, verbose_name='текст оформления заказа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='footer_text',
            field=models.TextField(blank=True, null=True, verbose_name='Footer text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='iframe_code',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес офисы'),
        ),
        migrations.AlterField(
            model_name='office',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='office',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='office',
            name='telegram',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='office',
            name='vkontakte',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='ВКонтакте'),
        ),
        migrations.AlterField(
            model_name='office',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='WhatsApp'),
        ),
    ]
