# Generated by Django 5.2.4 on 2025-08-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0027_cards_templateedit_sitesettings_checkout_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='is_about',
            field=models.BooleanField(default=False, verbose_name='О компании'),
        ),
    ]
