# Generated by Django 5.2.4 on 2025-08-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0028_cards_is_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.TextField(blank=True, null=True, verbose_name='About title')),
                ('about_subtitle', models.TextField(blank=True, null=True, verbose_name='About subtitle')),
                ('benefit_title', models.TextField(blank=True, null=True, verbose_name='преимущества title')),
                ('benefit_text', models.TextField(blank=True, null=True, verbose_name='преимущества text')),
                ('card1', models.TextField(blank=True, null=True, verbose_name='Card 1 text')),
                ('card2', models.TextField(blank=True, null=True, verbose_name='Card 2 text')),
                ('card1_img', models.ImageField(upload_to='media/sitesettings')),
                ('card2_img', models.ImageField(upload_to='media/sitesettings')),
                ('why_us_title', models.TextField(blank=True, null=True, verbose_name='почему мы title')),
                ('why_us', models.TextField(blank=True, null=True, verbose_name='почему мы')),
            ],
        ),
        migrations.CreateModel(
            name='PayCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_pay', models.TextField(blank=True, null=True, verbose_name='Оплата text')),
                ('payment_del', models.TextField(blank=True, null=True, verbose_name='Доставка  text')),
                ('payment_image', models.ImageField(upload_to='media/sitesettings')),
                ('delivery_image', models.ImageField(upload_to='media/sitesettings')),
            ],
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='benefit_text',
            field=models.TextField(default=2, verbose_name='Текст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='benefit_title',
            field=models.TextField(default=1, verbose_name='Почему выбирают нас'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(default=1, upload_to='manufacturers/', verbose_name='Логотип'),
            preserve_default=False,
        ),
    ]
