# Generated by Django 5.2.4 on 2025-08-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0029_about_page_paycheck_bannerimage_benefit_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField()),
            ],
        ),
    ]
