# Generated by Django 5.2.4 on 2025-08-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0030_privacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='число')),
                ('text', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='about_page',
            name='statistics',
            field=models.ManyToManyField(blank=True, null=True, related_name='stats', to='asic.aboutstat'),
        ),
    ]
