# Generated by Django 5.2.4 on 2025-08-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0031_aboutstat_about_page_statistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstat',
            name='text',
            field=models.CharField(max_length=30),
        ),
    ]
