# Generated by Django 5.2.4 on 2025-08-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0032_alter_aboutstat_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='banner_bg',
            field=models.ImageField(default=1, upload_to='media/sitesettings', verbose_name='Banner'),
            preserve_default=False,
        ),
    ]
