# Generated by Django 5.2.4 on 2025-08-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0033_about_page_banner_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='about_page',
            name='office_text',
            field=models.TextField(blank=True, null=True, verbose_name='Наши офисы text'),
        ),
        migrations.AddField(
            model_name='about_page',
            name='office_title',
            field=models.TextField(blank=True, null=True, verbose_name='Наши офисы title'),
        ),
    ]
