# Generated by Django 5.2.4 on 2025-08-28 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0034_about_page_office_text_about_page_office_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
    ]
