# Generated by Django 5.2.4 on 2025-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0035_discount_is_additional'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='payment_del_title',
            field=models.TextField(blank=True, null=True, verbose_name='Доставка  title'),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='payment_title',
            field=models.TextField(blank=True, null=True, verbose_name='Оплата title'),
        ),
    ]
