# Generated by Django 5.2.4 on 2025-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0036_paycheck_payment_del_title_paycheck_payment_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.CharField(blank=True, max_length=255, null=True, verbose_name='Главная страница')),
                ('catalog', models.CharField(blank=True, max_length=255, null=True, verbose_name='Каталог')),
                ('detail', models.CharField(blank=True, max_length=255, null=True, verbose_name='Детали продукта')),
                ('about', models.CharField(blank=True, max_length=255, null=True, verbose_name='О нас')),
                ('profile', models.CharField(blank=True, max_length=255, null=True, verbose_name='Профиль')),
                ('cart', models.CharField(blank=True, max_length=255, null=True, verbose_name='Корзина')),
                ('checkout', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оформление заказа')),
                ('privacy', models.CharField(blank=True, max_length=255, null=True, verbose_name='Политика конфиденциальности')),
                ('payment_deliver', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оплата и доставка')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Login')),
                ('register', models.CharField(blank=True, max_length=255, null=True, verbose_name='Register')),
            ],
            options={
                'verbose_name': 'Заголовок страниц',
                'verbose_name_plural': 'Заголовки страниц',
            },
        ),
    ]
