# Generated by Django 5.2.4 on 2025-09-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0037_pagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='home',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
