# Generated by Django 5.2.4 on 2025-09-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0038_profile_country_profile_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='max_order_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимальная сумма заказа'),
        ),
    ]
