# Generated by Django 5.2.4 on 2025-09-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0039_discount_max_order_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Информация о доставке', max_length=255)),
                ('courier_title', models.CharField(default='Курьерская доставка (5-7 дней)', max_length=255)),
                ('air_title', models.CharField(default='Авиа экспресс (3-5 дней)', max_length=255)),
                ('sea_title', models.CharField(default='Морская доставка (15-30 дней)', max_length=255)),
                ('main_text', models.CharField(blank=True, default='text', max_length=900, null=True, verbose_name='текст выше')),
                ('free_shipping_text', models.CharField(default='Бесплатно при заказе от $2000', max_length=255)),
                ('paid_shipping_text', models.CharField(default='До $2000 - $50-150 в зависимости от региона', max_length=255)),
                ('important_info_title', models.CharField(default='Важная информация:', max_length=255)),
                ('important_info_body', models.TextField(default='Все товары проходят предпродажную проверку и тестирование. Гарантируем работоспособность и соответствие заявленным характеристикам.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Доставка (контент)',
                'verbose_name_plural': 'Доставка (контент)',
            },
        ),
    ]
