# Generated by Django 5.2.4 on 2025-09-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0040_deliveryinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryinfo',
            name='main_text',
            field=models.TextField(blank=True, default='text', max_length=900, null=True, verbose_name='текст выше'),
        ),
    ]
