# Generated by Django 5.2.4 on 2025-09-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0041_alter_deliveryinfo_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='temprature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutstat',
            name='text',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deliveryinfo',
            name='main_text',
            field=models.CharField(blank=True, default='text', max_length=900, null=True, verbose_name='текст выше'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('air', 'Авиадоставка'), ('sea', 'Морская доставка'), ('auto', 'Авто доставка')], max_length=10, verbose_name='Тип доставки'),
        ),
    ]
