# Generated by Django 5.2.4 on 2025-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0042_product_temprature_alter_aboutstat_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('ready', 'Готов к отправке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20)),
                ('days_after', models.PositiveIntegerField(help_text='Necha kundan keyin ushbu statusga o‘tishi kerak')),
                ('order_priority', models.PositiveIntegerField(default=0, help_text='Tartib raqami (kichikroq birinchi bajariladi)')),
            ],
        ),
    ]
