# Generated by Django 5.2.4 on 2025-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0043_orderstatusrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatusrule',
            name='days_after',
            field=models.PositiveIntegerField(help_text='Сколько дней потребуется, чтобы достичь этого статуса?'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='order_priority',
            field=models.PositiveIntegerField(default=0, help_text='Порядковый номер (сначала выполняется наименьший)'),
        ),
    ]
