# Generated by Django 5.2.4 on 2025-09-26 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0044_alter_orderstatusrule_days_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
