# Generated by Django 5.2.4 on 2025-09-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0045_orderstatusrule_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, default=1, verbose_name='Дата последнего изменения статуса'),
            preserve_default=False,
        ),
    ]
