# Generated by Django 5.2.4 on 2025-09-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0047_add_last_status_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='last_status_update',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата последнего изменения статуса'),
        ),
    ]
