# Generated by Django 5.2.4 on 2025-09-28 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0048_alter_order_last_status_update'),
    ]

    operations = [
    ]
