# Generated by Django 5.2.4 on 2025-09-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0050_orderitem_discount_amount_orderitem_original_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('customs', 'На таможне'), ('sorting', 'В сортировочном центре'), ('delivering', 'Доставляется'), ('pickup_ready', 'Готов к выдаче'), ('ready', 'Готов к отправке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('customs', 'На таможне'), ('sorting', 'В сортировочном центре'), ('delivering', 'Доставляется'), ('pickup_ready', 'Готов к выдаче'), ('ready', 'Готов к отправке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatusrule',
            name='status',
            field=models.CharField(choices=[('new', 'Новый заказ'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('customs', 'На таможне'), ('sorting', 'В сортировочном центре'), ('delivering', 'Доставляется'), ('pickup_ready', 'Готов к выдаче'), ('ready', 'Готов к отправке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], max_length=20),
        ),
    ]
