# Generated by Django 5.2.4 on 2025-10-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asic', '0052_alter_order_status_alter_orderstatushistory_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusrule',
            name='immediate',
            field=models.BooleanField(default=False, verbose_name='Применять сразу при создании заказа?'),
        ),
    ]
